set -xeuo pipefail

export WANDB_API_KEY='YOUR_WANDB_API_KEY'
HOME='path/to/your/home'
model_scale='8B'    # '8B-Base', '4B', '8B'

exp_name='TRUSTEE-Qwen3-'${model_scale}'-Ablation-No-Curriculum'

n_rollout=8
train_batch_size=16
val_batch_size=16
mini_batch_size=4
micro_batch_size_per_gpu=1
n_gpus_per_node=4
n_nodes=1

max_prompt_length=8192
max_response_length=16384
max_token_len_per_gpu=$((${n_rollout}*${max_prompt_length}+${max_response_length}))

model_path=$HOME/model/Qwen/Qwen3-${model_scale}
train_dir=recipe/trustee/data/toolbench_tools.json
test_dir=recipe/trustee/data/valid.parquet

max_user_turns=3
max_assistant_turns=6
max_tool_turns=3
max_parallel_calls=3
max_tool_response_length=512

url=http://127.0.0.1:8000/v1
simulator_model=Qwen3-8B
max_tokens_tool=2048
max_tokens_user=2048
max_tokens_verifier=2048
timeout_tool=120
timeout_user=120
timeout_verifier=120
max_retries=3
frequency_penalty=0.1
verbose=false
enable_thinking=true
strip_thinking=false

difficulty_step=3
epsilon=0.5
multiplier_num_tools=0.10
multiplier_expected_tool_calls=0.03
multiplier_user_persona=0.02
multiplier_query_ambiguity=0.02
multiplier_expected_turns=0.02
multiplier_num_criteria=0.04
multiplier_system_prompt=0.03
multiplier_max_user_turns=0.03
multiplier_max_assistant_turns=0.06
multiplier_max_tool_turns=0.03
reward_threshold_upper=0.5
reward_threshold_lower=0.0

reward_mode=tgrpo
adv_estimator=tgrpo
adv_mode=uniform

enable_curriculum=True
enable_sampling_control=False

project_name='TRUSTEE'

CUDA_VISIBLE_DEVICES=0,1,2,3 python -m recipe.trustee.train \
    actor_rollout_ref.model.path=$model_path \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=${mini_batch_size} \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=${micro_batch_size_per_gpu} \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.actor.ppo_max_token_len_per_gpu=${max_token_len_per_gpu} \
    actor_rollout_ref.actor.fsdp_config.param_offload=True \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=${micro_batch_size_per_gpu} \
    actor_rollout_ref.rollout.tensor_model_parallel_size=${n_gpus_per_node} \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.temperature=1.0 \
    actor_rollout_ref.rollout.top_p=1.0 \
    actor_rollout_ref.rollout.top_k=-1 \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.8 \
    actor_rollout_ref.rollout.n=${n_rollout} \
    actor_rollout_ref.rollout.enforce_eager=True \
    actor_rollout_ref.rollout.max_model_len=$((${max_prompt_length} + ${max_response_length})) \
    actor_rollout_ref.rollout.log_prob_max_token_len_per_gpu=${max_token_len_per_gpu} \
    actor_rollout_ref.rollout.max_num_batched_tokens=$((${max_prompt_length} + ${max_response_length})) \
    actor_rollout_ref.rollout.val_kwargs.n=4 \
    actor_rollout_ref.rollout.val_kwargs.do_sample=True \
    actor_rollout_ref.rollout.val_kwargs.temperature=0.6 \
    actor_rollout_ref.rollout.val_kwargs.top_p=0.95 \
    actor_rollout_ref.rollout.val_kwargs.top_k=20 \
    actor_rollout_ref.rollout.multi_turn.max_user_turns=$max_user_turns \
    actor_rollout_ref.rollout.multi_turn.max_assistant_turns=$max_assistant_turns \
    actor_rollout_ref.rollout.multi_turn.max_tool_turns=$max_tool_turns \
    actor_rollout_ref.rollout.multi_turn.max_parallel_calls=$max_parallel_calls \
    actor_rollout_ref.rollout.multi_turn.max_tool_response_length=$max_tool_response_length \
    actor_rollout_ref.rollout.multi_turn.enable_tool_reward=True \
    actor_rollout_ref.rollout.multi_turn.enable_user_reward=True \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=${micro_batch_size_per_gpu} \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    actor_rollout_ref.ref.log_prob_max_token_len_per_gpu=${max_token_len_per_gpu} \
    algorithm.adv_estimator=$adv_estimator \
    algorithm.use_kl_in_reward=False \
    algorithm.adv_kwargs.mode=$adv_mode \
    critic.model.path=$model_path \
    critic.ppo_mini_batch_size=${mini_batch_size} \
    critic.ppo_micro_batch_size_per_gpu=${micro_batch_size_per_gpu} \
    critic.ppo_max_token_len_per_gpu=${max_token_len_per_gpu} \
    data.curriculum.enable=$enable_curriculum \
    data.curriculum.difficulty.step=$difficulty_step \
    data.curriculum.difficulty.level_initial=100 \
    data.curriculum.epsilon=$epsilon \
    data.curriculum.difficulty.multipliers.num_tools=$multiplier_num_tools \
    data.curriculum.difficulty.multipliers.expected_tool_calls=$multiplier_expected_tool_calls \
    data.curriculum.difficulty.multipliers.user_persona=$multiplier_user_persona \
    data.curriculum.difficulty.multipliers.query_ambiguity=$multiplier_query_ambiguity \
    data.curriculum.difficulty.multipliers.expected_turns=$multiplier_expected_turns \
    data.curriculum.difficulty.multipliers.num_criteria=$multiplier_num_criteria \
    data.curriculum.difficulty.multipliers.system_prompt=$multiplier_system_prompt \
    data.curriculum.difficulty.multipliers.max_user_turns=$multiplier_max_user_turns \
    data.curriculum.difficulty.multipliers.max_assistant_turns=$multiplier_max_assistant_turns \
    data.curriculum.difficulty.multipliers.max_tool_turns=$multiplier_max_tool_turns \
    data.curriculum.reward_threshold_upper=$reward_threshold_upper \
    data.curriculum.reward_threshold_lower=$reward_threshold_lower \
    data.train_files=$train_dir \
    data.val_files=$test_dir \
    data.train_batch_size=${train_batch_size} \
    data.val_batch_size=${val_batch_size} \
    data.max_prompt_length=${max_prompt_length} \
    data.max_response_length=${max_response_length} \
    data.filter_overlong_prompts=True \
    data.query_key=query \
    data.tools_key=tools \
    data.shuffle=True \
    reward_model.reward_manager=agent \
    reward_model.reward_kwargs.mode=$reward_mode \
    simulator.url=$url \
    simulator.api_key=dummy \
    simulator.model=$simulator_model \
    simulator.max_tokens.tool=$max_tokens_tool \
    simulator.max_tokens.user=$max_tokens_user \
    simulator.max_tokens.verifier=$max_tokens_verifier \
    simulator.timeout.tool=$timeout_tool \
    simulator.timeout.user=$timeout_user \
    simulator.timeout.verifier=$timeout_verifier \
    simulator.max_retries=$max_retries \
    simulator.frequency_penalty=$frequency_penalty \
    simulator.verbose=$verbose \
    simulator.enable_thinking=$enable_thinking \
    simulator.strip_thinking=$strip_thinking \
    sampling_control.enable=$enable_sampling_control \
    trainer.critic_warmup=0 \
    trainer.logger='["console", "wandb"]' \
    trainer.project_name=$project_name \
    trainer.experiment_name=$exp_name \
    trainer.n_gpus_per_node=${n_gpus_per_node} \
    trainer.nnodes=${n_nodes} \
    trainer.save_freq=50 \
    trainer.test_freq=200 \
    trainer.val_before_train=False \
    trainer.default_local_dir=$HOME/checkpoints/$project_name/$exp_name \
    trainer.validation_data_dir=generation/$project_name/$exp_name \
    trainer.total_training_steps=200 \
    trainer.total_epochs=1 $@
